<?php

use Nails\Factory;

if (!function_exists('app_notification'))
{
    /**
     * Get's emails associated with a particular group/key
     * @param  string  $key          The key to retrieve
     * @param  string  $grouping     The group the key belongs to
     * @param  boolean $forceRefresh Whether to force a group refresh
     * @return array
     */
    function app_notification($key = NULL, $grouping = 'app', $forceRefresh = FALSE)
    {
        $oAppNotificationModel = Factory::model('AppNotification');
        return $oAppNotificationModel->get($key, $grouping, $forceRefresh);
    }
}

// --------------------------------------------------------------------------

if (!function_exists('app_notification_notify'))
{
    /**
     * Sends a notification to the email addresses associated with a particular key/grouping
     * @param  string $key      The key to send to
     * @param  string $grouping The key's grouping
     * @param  array  $data     An array of values to pass to the email template
     * @param  array  $override Override any of the definition values (this time only). Useful for defining custom email templates etc.
     * @return boolean
     */
    function app_notification_notify($key = NULL, $grouping = 'app', $data = array(), $override = array())
    {
        $oAppNotificationModel = Factory::model('AppNotification');
        return $oAppNotificationModel->notify($key, $grouping, $data, $override);
    }
}

// --------------------------------------------------------------------------

if (!function_exists('app_notification_last_error'))
{
    /**
     * Retrieves the last error generated by the app notification model
     * @return string
     */
    function app_notification_last_error()
    {
        $oAppNotificationModel = Factory::model('AppNotification');
        return $oAppNotificationModel->last_error();
    }
}
