version: 2
updates:

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "hellopablo"
    labels:
      - "dependencies"
      - "php"
      - "automerge"

  # Maintain dependencies for NPM
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "hellopablo"
    labels:
      - "dependencies"
      - "npm"
      - "automerge"