<?php

/**
 * This class handles password protection of non-production environments
 *
 * The "is authenticated" state is held in a signed, self-contained cookie
 * rather than the session so that it survives session teardown (e.g. logging
 * out, or the session regeneration performed during MFA).
 *
 * @package     Nails
 * @subpackage  common
 * @category    Service
 * @author      Nails Dev Team
 * @link        https://docs.nailsapp.co.uk/key-concepts/environments#protecting-environments
 */

namespace Nails\Common\Service;

use Nails\Config;
use Nails\Environment;
use Nails\Factory;
use Nails\Functions;

/**
 * Class EnvironmentProtection
 *
 * @package Nails\Common\Service
 */
class EnvironmentProtection
{
    /**
     * The config keys which are suffixed with the environment being protected
     */
    const CONFIG_CREDENTIALS = 'APP_USER_PASS';
    const CONFIG_WHITELIST   = 'APP_USER_PASS_WHITELIST';
    const CONFIG_TTL         = 'APP_USER_PASS_TTL';

    /**
     * The config keys which apply to every environment
     */
    const CONFIG_COOKIE_NAME      = 'APP_USER_PASS_COOKIE_NAME';
    const CONFIG_COOKIE_DOMAIN    = 'APP_USER_PASS_COOKIE_DOMAIN';
    const CONFIG_COOKIE_SAME_SITE = 'APP_USER_PASS_COOKIE_SAME_SITE';
    const CONFIG_KEY_SALT         = 'APP_USER_PASS_KEY_SALT';
    const CONFIG_FIELD_USER       = 'APP_USER_PASS_FIELD_USER';
    const CONFIG_FIELD_PASS       = 'APP_USER_PASS_FIELD_PASS';
    const CONFIG_HEADER_USER      = 'APP_USER_PASS_HEADER_USER';
    const CONFIG_HEADER_PASS      = 'APP_USER_PASS_HEADER_PASS';

    /**
     * The cookie the token is stored in
     */
    const DEFAULT_COOKIE_NAME = 'nailsenvauth';

    /**
     * The token cookie's SameSite policy
     *
     * Lax, not Strict: the token must survive a top level navigation in from
     * an external link, otherwise arriving from an email would present the
     * gate again.
     */
    const DEFAULT_COOKIE_SAME_SITE = 'Lax';

    /**
     * Salts the private key so that this signature cannot be confused with
     * any other HMAC generated by the system
     *
     * Changing this invalidates every token which has been issued.
     */
    const DEFAULT_KEY_SALT = '/env-protection';

    /**
     * How long a token remains valid for, in seconds
     */
    const DEFAULT_TTL = 2592000;

    /**
     * The fields credentials can be supplied in via POST
     */
    const DEFAULT_FIELD_USER = 'AUTH_USER';
    const DEFAULT_FIELD_PASS = 'AUTH_PW';

    /**
     * The headers credentials can be supplied in
     */
    const DEFAULT_HEADER_USER = 'X-Auth-User';
    const DEFAULT_HEADER_PASS = 'X-Auth-Password';

    // --------------------------------------------------------------------------

    /**
     * The following properties are resolved from config on first use; they are
     * exposed as constructor arguments to make this class easier to test, and
     * as setters so that a controller can supply overridden values
     */
    protected ?array $aCredentials;
    protected ?array $aIpWhitelist;
    protected ?string $sEnvironment;
    protected ?int $iTtl;
    protected ?string $sPrivateKey;

    // --------------------------------------------------------------------------

    /**
     * EnvironmentProtection constructor.
     *
     * @param array|null  $aCredentials The credentials which unlock the environment
     * @param array|null  $aIpWhitelist IP addresses/ranges which bypass the gate
     * @param string|null $sEnvironment The environment being protected
     * @param int|null    $iTtl         How long a token remains valid for, in seconds
     * @param string|null $sPrivateKey  The key tokens are signed with
     */
    public function __construct(
        ?array $aCredentials = null,
        ?array $aIpWhitelist = null,
        ?string $sEnvironment = null,
        ?int $iTtl = null,
        ?string $sPrivateKey = null
    ) {
        $this->aCredentials = $aCredentials;
        $this->aIpWhitelist = $aIpWhitelist;
        $this->sEnvironment = $sEnvironment;
        $this->iTtl         = $iTtl;
        $this->sPrivateKey  = $sPrivateKey;
    }

    // --------------------------------------------------------------------------

    /**
     * Returns an array of key/value pairs which unlock the environment
     *
     * @return array
     */
    public function getCredentials(): array
    {
        if ($this->aCredentials === null) {
            $this->aCredentials = (array) $this->getConfig(static::CONFIG_CREDENTIALS, 'users');
        }

        return $this->aCredentials;
    }

    // --------------------------------------------------------------------------

    /**
     * Sets the credentials which unlock the environment
     *
     * @param array $aCredentials The credentials to set
     *
     * @return $this
     */
    public function setCredentials(array $aCredentials): self
    {
        $this->aCredentials = $aCredentials;
        return $this;
    }

    // --------------------------------------------------------------------------

    /**
     * Returns an array of whitelisted IP addresses/ranges
     *
     * @return array
     */
    public function getIpWhitelist(): array
    {
        if ($this->aIpWhitelist === null) {
            $this->aIpWhitelist = (array) $this->getConfig(static::CONFIG_WHITELIST, 'whitelist');
        }

        return $this->aIpWhitelist;
    }

    // --------------------------------------------------------------------------

    /**
     * Sets the whitelisted IP addresses/ranges
     *
     * @param array $aIpWhitelist The whitelist to set
     *
     * @return $this
     */
    public function setIpWhitelist(array $aIpWhitelist): self
    {
        $this->aIpWhitelist = $aIpWhitelist;
        return $this;
    }

    // --------------------------------------------------------------------------

    /**
     * Resolves a config value, falling back to a JSON file in the app root
     *
     * @param string $sConfigKey The config key, sans environment
     * @param string $sFileType  The type of protect.*.json file to fall back to
     *
     * @return mixed
     */
    protected function getConfig(string $sConfigKey, string $sFileType)
    {
        $mConfig = Config::get($sConfigKey . '_' . $this->getEnvironment());
        $sFile   = sprintf('protect.%s.%s.json', strtolower($this->getEnvironment()), $sFileType);

        if ($mConfig === null && file_exists($sFile)) {
            $mConfig = @json_decode(file_get_contents($sFile)) ?? [];
        }

        return $mConfig;
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the environment being protected
     *
     * @return string
     */
    public function getEnvironment(): string
    {
        if ($this->sEnvironment === null) {
            $this->sEnvironment = Environment::get();
        }

        return $this->sEnvironment;
    }

    // --------------------------------------------------------------------------

    /**
     * Returns how long a token remains valid for, in seconds
     *
     * @return int
     */
    public function getTtl(): int
    {
        if ($this->iTtl === null) {
            $this->iTtl = (int) Config::get(
                static::CONFIG_TTL . '_' . $this->getEnvironment(),
                static::DEFAULT_TTL
            );
        }

        return $this->iTtl;
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the key tokens are signed with
     *
     * @return string
     */
    protected function getKey(): string
    {
        if ($this->sPrivateKey === null) {
            $this->sPrivateKey = (string) Config::get('PRIVATE_KEY');
        }

        return $this->sPrivateKey . $this->getKeySalt();
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the salt applied to the private key
     *
     * Doubles as a means of invalidating every token which has been issued:
     * change it and no existing signature will verify.
     *
     * @return string
     */
    protected function getKeySalt(): string
    {
        return (string) Config::get(static::CONFIG_KEY_SALT, static::DEFAULT_KEY_SALT);
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the name of the cookie the token is stored in
     *
     * @return string
     */
    public function getCookieName(): string
    {
        return (string) Config::get(static::CONFIG_COOKIE_NAME, static::DEFAULT_COOKIE_NAME);
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the domain the token cookie is scoped to
     *
     * Defaults to host only, which is correct unless the app is served from
     * more than one host.
     *
     * @return string
     */
    public function getCookieDomain(): string
    {
        return (string) Config::get(
            static::CONFIG_COOKIE_DOMAIN,
            Config::get('CONF_COOKIE_DOMAIN', '')
        );
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the token cookie's SameSite policy
     *
     * @return string
     */
    public function getCookieSameSite(): string
    {
        return (string) Config::get(static::CONFIG_COOKIE_SAME_SITE, static::DEFAULT_COOKIE_SAME_SITE);
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the POST field the username is supplied in
     *
     * @return string
     */
    public function getFieldUser(): string
    {
        return (string) Config::get(static::CONFIG_FIELD_USER, static::DEFAULT_FIELD_USER);
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the POST field the password is supplied in
     *
     * @return string
     */
    public function getFieldPass(): string
    {
        return (string) Config::get(static::CONFIG_FIELD_PASS, static::DEFAULT_FIELD_PASS);
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the header the username can be supplied in
     *
     * @return string
     */
    public function getHeaderUser(): string
    {
        return (string) Config::get(static::CONFIG_HEADER_USER, static::DEFAULT_HEADER_USER);
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the header the password can be supplied in
     *
     * @return string
     */
    public function getHeaderPass(): string
    {
        return (string) Config::get(static::CONFIG_HEADER_PASS, static::DEFAULT_HEADER_PASS);
    }

    // --------------------------------------------------------------------------

    /**
     * Whether the environment is password protected
     *
     * @return bool
     */
    public function isProtected(): bool
    {
        return !empty($this->getCredentials());
    }

    // --------------------------------------------------------------------------

    /**
     * Whether the request originates from a whitelisted IP address
     *
     * @return bool
     * @throws \Nails\Common\Exception\FactoryException
     */
    public function isWhitelisted(): bool
    {
        $aIpWhitelist = $this->getIpWhitelist();

        if (empty($aIpWhitelist)) {
            return false;
        }

        /** @var Input $oInput */
        $oInput = Factory::service('Input');

        return isIpInRange($oInput->ipAddress(), $aIpWhitelist);
    }

    // --------------------------------------------------------------------------

    /**
     * Whether the supplied credentials unlock the environment
     *
     * @param string|null $sUser The username to test
     * @param string|null $sPass The password to test
     *
     * @return bool
     */
    public function verifyCredentials(?string $sUser, ?string $sPass): bool
    {
        $aCredentials = $this->getCredentials();

        if ($sUser === null || $sPass === null || !array_key_exists($sUser, $aCredentials)) {
            return false;
        }

        return $this->verifyPassword($sPass, (string) $aCredentials[$sUser]);
    }

    // --------------------------------------------------------------------------

    /**
     * Compares a password against a stored hash
     *
     * Hashes generated by password_hash() are supported, as is the legacy
     * unsalted sha256 digest.
     *
     * @param string $sPass The password to test
     * @param string $sHash The hash to test against
     *
     * @return bool
     */
    protected function verifyPassword(string $sPass, string $sHash): bool
    {
        //  password_hash() output is identified by its `$algo$` prefix
        if (preg_match('/^\$[a-z0-9]/i', $sHash)) {
            return password_verify($sPass, $sHash);
        }

        return hash_equals($sHash, hash('sha256', $sPass));
    }

    // --------------------------------------------------------------------------

    /**
     * Generates a token for the given user
     *
     * @param string   $sUser The user to generate a token for
     * @param int|null $iNow  The time to treat as now
     *
     * @return string
     */
    public function generateToken(string $sUser, ?int $iNow = null): string
    {
        $sPayload = $this->base64UrlEncode(
            json_encode([
                'u' => $sUser,
                'e' => $this->getEnvironment(),
                'x' => ($iNow ?? time()) + $this->getTtl(),
                'f' => $this->getFingerprint($sUser),
            ])
        );

        return $sPayload . '.' . $this->base64UrlEncode($this->sign($sPayload));
    }

    // --------------------------------------------------------------------------

    /**
     * Validates a token, returning the user it was issued to
     *
     * @param string|null $sToken The token to validate
     * @param int|null    $iNow   The time to treat as now
     *
     * @return string|null
     */
    public function validateToken(?string $sToken, ?int $iNow = null): ?string
    {
        $aPayload = $this->decodeToken($sToken);

        if ($aPayload === null) {
            return null;
        }

        $sUser = $aPayload['u'] ?? null;

        if (!is_string($sUser) || $sUser === '') {
            return null;

        } elseif (($aPayload['e'] ?? null) !== $this->getEnvironment()) {
            //  A token issued for another environment
            return null;

        } elseif ((int) ($aPayload['x'] ?? 0) <= ($iNow ?? time())) {
            return null;

        } elseif (!array_key_exists($sUser, $this->getCredentials())) {
            //  The user has been removed
            return null;

        } elseif (!hash_equals($this->getFingerprint($sUser), (string) ($aPayload['f'] ?? ''))) {
            //  The user's password has changed
            return null;
        }

        return $sUser;
    }

    // --------------------------------------------------------------------------

    /**
     * Whether a token is close enough to expiry that it should be reissued
     *
     * @param string|null $sToken The token to test
     * @param int|null    $iNow   The time to treat as now
     *
     * @return bool
     */
    public function shouldRenewToken(?string $sToken, ?int $iNow = null): bool
    {
        $aPayload = $this->decodeToken($sToken);

        if ($aPayload === null) {
            return false;
        }

        //  Reissue once the token is past its half life
        return ((int) ($aPayload['x'] ?? 0) - ($iNow ?? time())) < ($this->getTtl() / 2);
    }

    // --------------------------------------------------------------------------

    /**
     * Verifies a token's signature and returns its payload
     *
     * @param string|null $sToken The token to decode
     *
     * @return array|null
     */
    protected function decodeToken(?string $sToken): ?array
    {
        if (empty($sToken) || substr_count($sToken, '.') !== 1) {
            return null;
        }

        [$sPayload, $sSignature] = explode('.', $sToken);

        if (!hash_equals($this->base64UrlEncode($this->sign($sPayload)), $sSignature)) {
            return null;
        }

        $aPayload = json_decode($this->base64UrlDecode($sPayload), true);

        return is_array($aPayload) ? $aPayload : null;
    }

    // --------------------------------------------------------------------------

    /**
     * Signs a payload
     *
     * @param string $sPayload The payload to sign
     *
     * @return string
     */
    protected function sign(string $sPayload): string
    {
        return hash_hmac('sha256', $sPayload, $this->getKey(), true);
    }

    // --------------------------------------------------------------------------

    /**
     * Fingerprints a user's stored hash so that changing, or removing, their
     * password invalidates any token already issued to them
     *
     * @param string $sUser The user to fingerprint
     *
     * @return string
     */
    protected function getFingerprint(string $sUser): string
    {
        $aCredentials = $this->getCredentials();

        return substr(
            hash_hmac('sha256', (string) ($aCredentials[$sUser] ?? ''), $this->getKey()),
            0,
            16
        );
    }

    // --------------------------------------------------------------------------

    /**
     * Whether the request carries a valid token
     *
     * Renews the token if it is past its half life, so that active users are
     * not periodically asked to re-authenticate.
     *
     * @return bool
     * @throws \Nails\Common\Exception\FactoryException
     */
    public function isAuthenticated(): bool
    {
        $sToken = $this->getTokenFromRequest();
        $sUser  = $this->validateToken($sToken);

        if ($sUser === null) {
            return false;

        } elseif ($this->shouldRenewToken($sToken)) {
            $this->issueToken($sUser);
        }

        return true;
    }

    // --------------------------------------------------------------------------

    /**
     * Discards the token, requiring the user to authenticate again
     *
     * @return $this
     * @throws \Nails\Common\Exception\FactoryException
     */
    public function signOut(): self
    {
        /** @var Cookie $oCookie */
        $oCookie = Factory::service('Cookie');
        $oCookie->delete($this->getCookieName(), '/', $this->getCookieDomain());

        return $this;
    }

    // --------------------------------------------------------------------------

    /**
     * Returns any credentials supplied by the request, be that via basic auth,
     * headers, or the login form
     *
     * @return array{0: string|null, 1: string|null}
     * @throws \Nails\Common\Exception\FactoryException
     */
    public function getCredentialsFromRequest(): array
    {
        /** @var Input $oInput */
        $oInput = Factory::service('Input');

        $mUser = $oInput->server('PHP_AUTH_USER')
            ?: $oInput->header($this->getHeaderUser())
                ?: $oInput->post($this->getFieldUser());

        $mPass = $oInput->server('PHP_AUTH_PW')
            ?: $oInput->header($this->getHeaderPass())
                ?: $oInput->post($this->getFieldPass());

        return [
            $mUser ? (string) $mUser : null,
            $mPass ? (string) $mPass : null,
        ];
    }

    // --------------------------------------------------------------------------

    /**
     * Returns the token supplied by the request, if any
     *
     * @return string|null
     * @throws \Nails\Common\Exception\FactoryException
     */
    public function getTokenFromRequest(): ?string
    {
        /** @var Cookie $oCookie */
        $oCookie = Factory::service('Cookie');
        $oToken  = $oCookie->read($this->getCookieName());

        return $oToken ? (string) $oToken->value : null;
    }

    // --------------------------------------------------------------------------

    /**
     * Issues a token for the given user
     *
     * The caller is responsible for having verified the user's credentials.
     *
     * @param string $sUser The user to issue a token for
     *
     * @return $this
     * @throws \Nails\Common\Exception\FactoryException
     */
    public function issueToken(string $sUser): self
    {
        /** @var Cookie $oCookie */
        $oCookie = Factory::service('Cookie');
        $oCookie->write(
            $this->getCookieName(),
            $this->generateToken($sUser),
            $this->getTtl(),
            '/',
            $this->getCookieDomain(),
            Functions::isPageSecure(),
            true,
            $this->getCookieSameSite()
        );

        return $this;
    }

    // --------------------------------------------------------------------------

    /**
     * Encodes a value using the URL safe base64 alphabet
     *
     * @param string $sValue The value to encode
     *
     * @return string
     */
    protected function base64UrlEncode(string $sValue): string
    {
        return rtrim(strtr(base64_encode($sValue), '+/', '-_'), '=');
    }

    // --------------------------------------------------------------------------

    /**
     * Decodes a value using the URL safe base64 alphabet
     *
     * @param string $sValue The value to decode
     *
     * @return string
     */
    protected function base64UrlDecode(string $sValue): string
    {
        return (string) base64_decode(strtr($sValue, '-_', '+/'));
    }
}
